let a = {
  ver: 'registroVenta',
  tipoventa: '1',
  idusuario: '03afdbd66e7929b125f8597834fa83a4',
  idempresa: 'c0c7c76d30bd3dcaefc96f40275bdc0a',
  idcliente: '1012',
  sucursal: '854',
  tipodoc: '1',
  nrodoc: '4512544',
  fecha: '2025-09-17',
  puntoventa: '107',
  metodoPago: '1',
  canal: '98',
  tipopago: 'contado',
  periodopersonalizado: '0',
  jsonDetalles: {
    listaProductos: [
      {
        idproductoalmacen: '3388',
        cantidad: 1,
        precio: '12',
        idstock: '5176',
        idporcentaje: '153',
        candiponible: '12',
        descripcion: 'Teclado inalambrico',
        codigo: 'LP01',
        id: '3388',
        subtotal: 12,
        datosAdicionales: '99760--57-',
        despachado: 1,
      },
    ],
    listaProductosFactura: [
      {
        codigoProducto: 'LP01',
        codigoActividadSin: '',
        codigoProductoSin: '99760',
        descripcion: 'Teclado inalambrico',
        unidadMedida: '57',
        precioUnitario: '12',
        subTotal: '12.00',
        cantidad: 1,
        numeroSerie: '',
        montoDescuento: 0,
        numeroImei: '',
        codigoNandina: '',
      },
    ],
    listaFactura: {
      nombreRazonSocial: 'Juan Jose',
      codigoCliente: 'JE-500011',
      numeroDocumento: '4512544',
      codigoTipoDocumentoIdentidad: '1',
      telefonoCliente: '',
      codigoPuntoVenta: '107',
      codigoMetodoPago: 1,
      fechaEmision: '2025-09-17T16:01:38.446Z',
    },
    idalmacen: 93,
    codigosinsucursal: '0',
    token:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzMDAzMzUiLCJqdGkiOiJjYjE2NDUzNTc4ZGRhYTgwNmFhMWEyNDcxMGYxZTI3OWQyODU1MGM5ZGE4MTAwNmVmNmIyYjU1YTI3MDc4ZDRjYzNjODkwZTU2NGIxZDVjNyIsImlhdCI6MTc0MjQ3NTY2NCwibmJmIjoxNzQyNDc1NjY0LCJleHAiOjE3NzQwMTE2NjQsInN1YiI6IiIsInNjb3BlcyI6W119.KFugkzjz4rXPCRsMl23sAIrDkYRuOwAJi9W0WUGg1XthO4ZvGJTsU-8ifEQYdudyIZ_b-zy49NL7fhbKoxtNVoBZbtuoYDTzCZN3Jb0Jsc3enVL_YezYr_5vA8qBBRvYdyihqTjvRQt9dYVP--QtrLp0qtQ8wP_vUyNTQh9POJUZhMd6EXjjxG_6tfgAzVOYbVty_WFU0xXDkReYLfphjqFRLPo-3vWlo5god5ixYMM55PWXLnz01bYlJREhJ-U-z46_klvgfAbdGs_EdIeBSUlYfXOn0NOWHP5Q6QlVt85ajFLByd1uv5jVW3IsDzrMkfvf1u-4YCeOkPFqU3WMvAia46nVjLnpfBNERqYEnlwmiMnNoZ2HDDiHDJyy7i8ADDGy_pS-i6SItZ6yE9Qk3MfX6xYO5bxBZXFpozSxLlVytk3qeq3tuBr9H_QXbW3G-yQzk2mHTK7iMRX8Lzm6uZuJed60MpnzekEiKQBNIWdYgp9v5BmvYHHRyvjoMn5cI2LV9RNJVKB11Z2tQHSeeY61bo9u3aGJ094v3BRpnRiIffJEP-7jo7zpvAxz3AS5bS_lFaOdfU2LboJSTAWVefTHw9JFnHnTRQZSBJ_EDqnOJrQhS6vjYa1zGtHti4Qs8U1U4cqcTn-pyzL0lqltfsdGbaBU5UE4RcsiB2eKzhs',
    tipo: '1',
    iddivisa: null,
    idcampana: 0,
    ventatotal: '12.00',
    subtotal: '12.00',
    descuento: 0,
    nropagos: 0,
    valorpagos: 0,
    dias: null,
    fechalimite: '',
    pagosDivididos: [
      {
        metodoPago: {
          label: 'Efectivo',
          id: 1,
          value: '7',
        },
        monto: '12.00',
        porcentaje: 100,
      },
    ],
    variablePago: 'dividido',
    puntoVenta: '111',
    puntoVentaSin: '107',
    idleyenda: '20',
  },
}
console.log(JSON.stringify(a))

const req = {
  fecha: '2025-09-17',
  tipoventa: '1',
  tipopago: 'contado',
  idcliente: '281',
  idsucursal: '256',
  canalventa: '98',
  idmd5: 'c0c7c76d30bd3dcaefc96f40275bdc0a',
  idmd5u: '03afdbd66e7929b125f8597834fa83a4',
  jsonDetalles: {
    listaProductos: [
      {
        idproductoalmacen: '3388',
        cantidad: 1,
        precio: '4500',
        idstock: '5181',
        idporcentaje: '152',
        candiponible: '10',
        descripcion: 'Teclado inalambrico',
        codigo: 'LP01',
        id: '3388',
        subtotal: 4500,
        datosAdicionales: '99760--57-',
        despachado: 1,
      },
    ],
    listaProductosFactura: [
      {
        codigoProducto: 'LP01',
        codigoActividadSin: '',
        codigoProductoSin: '99760',
        descripcion: 'Teclado inalambrico',
        unidadMedida: '57',
        precioUnitario: '4500',
        subTotal: '4500.00',
        cantidad: 1,
        numeroSerie: '',
        montoDescuento: 0,
        numeroImei: '',
        codigoNandina: '',
      },
    ],
    listaFactura: {
      numeroFactura: '',
      nombreRazonSocial: 'Fundación Arco Iris',
      codigoPuntoVenta: '107',
      fechaEmision: '2025-09-17T16:55:47.974Z',
      cafc: '',
      codigoExcepcion: '',
      descuentoAdicional: 0,
      montoGiftCard: 0,
      codigoTipoDocumentoIdentidad: '5',
      numeroDocumento: '328702024',
      complemento: '',
      codigoCliente: 'FS-500001',
      periodoFacturado: '',
      codigoLeyenda: 248,
      codigoMetodoPago: '10',
      numeroTarjeta: '',
      montoTotal: '4500.00',
      codigoMoneda: 1,
      montoTotalMoneda: '4500.00',
      usuario: 'richard50',
      emailCliente: 'factura@yofinanciero.com',
      telefonoCliente: '45689655',
      extras: {
        facturaTicket: '',
      },
      montoTotalSujetoIva: '4500.00',
      tipoCambio: 1,
      detalles: [
        {
          codigoProducto: 'LP01',
          codigoActividadSin: '',
          codigoProductoSin: '99760',
          descripcion: 'Teclado inalambrico',
          unidadMedida: '57',
          precioUnitario: '4500',
          subTotal: '4500.00',
          cantidad: 1,
          numeroSerie: '',
          montoDescuento: 0,
          numeroImei: '',
          codigoNandina: '',
        },
      ],
    },
    idalmacen: 93,
    codigosinsucursal: '0',
    token:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzMDAzMzUiLCJqdGkiOiJjYjE2NDUzNTc4ZGRhYTgwNmFhMWEyNDcxMGYxZTI3OWQyODU1MGM5ZGE4MTAwNmVmNmIyYjU1YTI3MDc4ZDRjYzNjODkwZTU2NGIxZDVjNyIsImlhdCI6MTc0MjQ3NTY2NCwibmJmIjoxNzQyNDc1NjY0LCJleHAiOjE3NzQwMTE2NjQsInN1YiI6IiIsInNjb3BlcyI6W119.KFugkzjz4rXPCRsMl23sAIrDkYRuOwAJi9W0WUGg1XthO4ZvGJTsU-8ifEQYdudyIZ_b-zy49NL7fhbKoxtNVoBZbtuoYDTzCZN3Jb0Jsc3enVL_YezYr_5vA8qBBRvYdyihqTjvRQt9dYVP--QtrLp0qtQ8wP_vUyNTQh9POJUZhMd6EXjjxG_6tfgAzVOYbVty_WFU0xXDkReYLfphjqFRLPo-3vWlo5god5ixYMM55PWXLnz01bYlJREhJ-U-z46_klvgfAbdGs_EdIeBSUlYfXOn0NOWHP5Q6QlVt85ajFLByd1uv5jVW3IsDzrMkfvf1u-4YCeOkPFqU3WMvAia46nVjLnpfBNERqYEnlwmiMnNoZ2HDDiHDJyy7i8ADDGy_pS-i6SItZ6yE9Qk3MfX6xYO5bxBZXFpozSxLlVytk3qeq3tuBr9H_QXbW3G-yQzk2mHTK7iMRX8Lzm6uZuJed60MpnzekEiKQBNIWdYgp9v5BmvYHHRyvjoMn5cI2LV9RNJVKB11Z2tQHSeeY61bo9u3aGJ094v3BRpnRiIffJEP-7jo7zpvAxz3AS5bS_lFaOdfU2LboJSTAWVefTHw9JFnHnTRQZSBJ_EDqnOJrQhS6vjYa1zGtHti4Qs8U1U4cqcTn-pyzL0lqltfsdGbaBU5UE4RcsiB2eKzhs',
    tipo: '1',
    iddivisa: 138,
    idcampana: 0,
    ventatotal: '4500.00',
    subtotal: '4500.00',
    descuento: 0,
    nropagos: 0,
    valorpagos: 0,
    dias: null,
    fechalimite: '',
    pagosDivididos: [
      {
        metodoPago: {
          label: 'Efectivo',
          id: 1,
          value: '7',
        },
        monto: '4500.00',
        porcentaje: 100,
      },
    ],
    variablePago: 'dividido',
    puntoVenta: '111',
    puntoVentaSin: '107',
    idleyenda: '20',
  },
}

const req2 = {
  fecha: '2025-09-17',
  tipoventa: '1',
  tipopago: 'contado',
  idcliente: '281',
  idsucursal: '256',
  canalventa: '98',
  idmd5: 'c0c7c76d30bd3dcaefc96f40275bdc0a',
  idmd5u: '03afdbd66e7929b125f8597834fa83a4',
  jsonDetalles: {
    listaProductos: [
      {
        idproductoalmacen: '3388',
        cantidad: 1,
        precio: '4500',
        idstock: '5181',
        idporcentaje: '152',
        candiponible: '10',
        descripcion: 'Teclado inalambrico',
        codigo: 'LP01',
        id: '3388',
        subtotal: 4500,
        datosAdicionales: '99760--57-',
        despachado: 1,
      },
    ],
    listaProductosFactura: [
      {
        codigoProducto: 'LP01',
        codigoActividadSin: '',
        codigoProductoSin: '99760',
        descripcion: 'Teclado inalambrico',
        unidadMedida: '57',
        precioUnitario: '4500',
        subTotal: '4500.00',
        cantidad: 1,
        numeroSerie: '',
        montoDescuento: 0,
        numeroImei: '',
        codigoNandina: '',
      },
    ],
    listaFactura: {
      numeroFactura: '',
      nombreRazonSocial: 'Fundación Arco Iris',
      codigoPuntoVenta: '107',
      fechaEmision: '2025-09-17T16:55:47.974Z',
      cafc: '',
      codigoExcepcion: '',
      descuentoAdicional: 0,
      montoGiftCard: 0,
      codigoTipoDocumentoIdentidad: '5',
      numeroDocumento: '328702024',
      complemento: '',
      codigoCliente: 'FS-500001',
      periodoFacturado: '',
      codigoLeyenda: 248,
      codigoMetodoPago: 1,
      numeroTarjeta: '',
      montoTotal: '4500.00',
      codigoMoneda: 1,
      montoTotalMoneda: '4500.00',
      usuario: 'richard50',
      emailCliente: 'factura@yofinanciero.com',
      telefonoCliente: '45689655',
      extras: {
        facturaTicket: '',
      },
      montoTotalSujetoIva: '4500.00',
      tipoCambio: 1,
      detalles: [
        {
          codigoProducto: 'LP01',
          codigoActividadSin: '',
          codigoProductoSin: '99760',
          descripcion: 'Teclado inalambrico',
          unidadMedida: '57',
          precioUnitario: '4500',
          subTotal: '4500.00',
          cantidad: 1,
          numeroSerie: '',
          montoDescuento: 0,
          numeroImei: '',
          codigoNandina: '',
        },
      ],
    },
    idalmacen: 93,
    codigosinsucursal: '0',
    token:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzMDAzMzUiLCJqdGkiOiJjYjE2NDUzNTc4ZGRhYTgwNmFhMWEyNDcxMGYxZTI3OWQyODU1MGM5ZGE4MTAwNmVmNmIyYjU1YTI3MDc4ZDRjYzNjODkwZTU2NGIxZDVjNyIsImlhdCI6MTc0MjQ3NTY2NCwibmJmIjoxNzQyNDc1NjY0LCJleHAiOjE3NzQwMTE2NjQsInN1YiI6IiIsInNjb3BlcyI6W119.KFugkzjz4rXPCRsMl23sAIrDkYRuOwAJi9W0WUGg1XthO4ZvGJTsU-8ifEQYdudyIZ_b-zy49NL7fhbKoxtNVoBZbtuoYDTzCZN3Jb0Jsc3enVL_YezYr_5vA8qBBRvYdyihqTjvRQt9dYVP--QtrLp0qtQ8wP_vUyNTQh9POJUZhMd6EXjjxG_6tfgAzVOYbVty_WFU0xXDkReYLfphjqFRLPo-3vWlo5god5ixYMM55PWXLnz01bYlJREhJ-U-z46_klvgfAbdGs_EdIeBSUlYfXOn0NOWHP5Q6QlVt85ajFLByd1uv5jVW3IsDzrMkfvf1u-4YCeOkPFqU3WMvAia46nVjLnpfBNERqYEnlwmiMnNoZ2HDDiHDJyy7i8ADDGy_pS-i6SItZ6yE9Qk3MfX6xYO5bxBZXFpozSxLlVytk3qeq3tuBr9H_QXbW3G-yQzk2mHTK7iMRX8Lzm6uZuJed60MpnzekEiKQBNIWdYgp9v5BmvYHHRyvjoMn5cI2LV9RNJVKB11Z2tQHSeeY61bo9u3aGJ094v3BRpnRiIffJEP-7jo7zpvAxz3AS5bS_lFaOdfU2LboJSTAWVefTHw9JFnHnTRQZSBJ_EDqnOJrQhS6vjYa1zGtHti4Qs8U1U4cqcTn-pyzL0lqltfsdGbaBU5UE4RcsiB2eKzhs',
    tipo: '1',
    iddivisa: 138,
    idcampana: 0,
    ventatotal: '4500.00',
    subtotal: '4500.00',
    descuento: 0,
    nropagos: 0,
    valorpagos: 0,
    dias: null,
    fechalimite: '',
    pagosDivididos: [
      {
        metodoPago: {
          label: 'Efectivo',
          id: 1,
          value: '7',
        },
        monto: '4500.00',
        porcentaje: 100,
      },
    ],
    variablePago: 'dividido',
    puntoVenta: '111',
    puntoVentaSin: '107',
    idleyenda: '20',
  },
}

console.log(JSON.stringify(req))
console.log(JSON.stringify(req2))
