// Configuración de versiones del sistema
export const versionesConfig = [
  {
    id: 1,
    title: 'v1.0',
    date: '14 ENE 2026',
    icon: 'rocket_launch',
    status: true,
    statusName: 'Publicado',
    statusColor: 'primary',
    statusIcon: 'check_circle',
    content: 'v1.0',
    isNew: false,
    features: [
      'Filtros avanzados en tablas principales (Fecha, Numéricos, Texto).',
      'Botones de acceso rápido en cabeceras de columnas.',
      'Optimización de rendimiento en carga de reportes.',
      'Nueva interfaz de usuario más limpia y amigable.',
    ],
    modules: [
      { name: 'Compras', tooltip: 'Reporte de Compras Desglosado', icon: 'shopping_cart' },
      { name: 'Stock', tooltip: 'Reporte individual de productos', icon: 'inventory_2' },
      { name: 'Ventas', tooltip: 'Ventas y Contingencias', icon: 'point_of_sale' },
      { name: 'Anulaciones', tooltip: 'Gestión de devoluciones', icon: 'remove_shopping_cart' },
    ],
    videoUrl: 'https://www.youtube.com/embed/bvTBbz2AdFQ?si=RhtXAXCnJsx5AQFI',
  },
  {
    id: 2,
    title: 'v1.1',
    date: '03 FEB 2026',
    icon: 'inventory',
    status: true,
    statusName: 'Publicado',
    statusColor: 'primary',
    statusIcon: 'check_circle',
    content: 'v1.1',
    isNew: true,
    features: [
      'Select de filtro sincronizado entre Tabla y Pedidos Movimiento.',
      'Checkboxes para envío masivo de pedidos con mismo destino.',
      'Validación automática de destinos incompatibles.',
      'Actualización automática de tabla sin recargar página.',
      'Visualización de productos acumulados antes de enviar.',
      'Comentarios múltiples separados por punto y coma en Descripción.',
      'Generación de PDF del pedido para reporte físico o digital.',
    ],
    modules: [
      { name: 'Movimientos', tooltip: 'Gestión de movimientos de almacén', icon: 'local_shipping' },
      { name: 'Pedidos', tooltip: 'Pedidos de movimiento entre almacenes', icon: 'shopping_bag' },
      { name: 'Reportes', tooltip: 'Generación de PDF de pedidos', icon: 'picture_as_pdf' },
      { name: 'Almacenes', tooltip: 'Sincronización de almacenes', icon: 'warehouse' },
    ],
    videoUrl: 'https://www.youtube.com/embed/v7wT0NREf-0?si=aHJpH-SFyANYhYz9', // Reemplazar con el ID real del video
  },
  /**{
    id: 3,
    title: 'Próximamente',
    date: 'En desarrollo',
    icon: 'construction',
    status: true,
    statusName: 'En Progreso',
    statusColor: 'orange',
    statusIcon: 'engineering',
    content: 'future',
    isNew: false,
  },*/
  {
    id: 3,
    title: 'v1.2',
    date: '10 SEP 2026',
    icon: 'category',
    status: true,
    statusName: 'Publicado',
    statusColor: 'primary',
    statusIcon: 'check_circle',
    content: 'v1.2',
    isNew: true,
    features: [
      'Creación de nuevas series para organizar productos variantes.',
      'Asociación de productos variantes a una serie según el modelo de producto.',
      'Selección individual o masiva de productos variantes.',
      'Filtros por atributos como color y talla para facilitar la selección de variantes.',
      'Consulta del detalle de una serie y los productos variantes asociados.',
      'Permite agrupar variantes de un mismo modelo en diferentes series.',
    ],
    modules: [
      {
        name: 'Productos y servicios',
        tooltip: 'Gestión y agrupación de productos variantes',
        icon: 'inventory_2',
      },
      {
        name: 'Series',
        tooltip: 'Creación y gestión de series de productos',
        icon: 'category',
      },
      {
        name: 'Variantes',
        tooltip: 'Selección y asociación de productos variantes',
        icon: 'view_list',
      },
    ],
    videoUrl: 'https://www.youtube.com/embed/wqzBkRMXzP0',
  },
  {
    id: 4,
    title: 'v1.3',
    date: '10 SEP 2026',
    icon: 'shopping_cart',
    status: true,
    statusName: 'Publicado',
    statusColor: 'primary',
    statusIcon: 'check_circle',
    content: 'v1.3',
    isNew: true,
    features: [
      'Registro de nuevas compras asociadas a un almacén.',
      'Selección del proveedor y forma de pago durante el registro de la compra.',
      'Carga de productos mediante la opción Añadir al carrito.',
      'Visualización de productos variantes según el modelo seleccionado.',
      'Filtro por series para localizar rápidamente productos variantes.',
      'Registro de precio y cantidad para cada producto variante.',
      'Ingreso al carrito únicamente de las variantes cuya cantidad sea mayor que cero.',
      'Carga de las cantidades registradas al inventario del almacén seleccionado.',
    ],
    modules: [
      {
        name: 'Compras',
        tooltip: 'Registro y gestión de compras',
        icon: 'shopping_cart',
      },
      {
        name: 'Inventario',
        tooltip: 'Ingreso de productos al inventario',
        icon: 'inventory_2',
      },
      {
        name: 'Productos',
        tooltip: 'Selección de modelos y productos variantes',
        icon: 'category',
      },
      {
        name: 'Series',
        tooltip: 'Filtro de productos variantes por serie',
        icon: 'filter_alt',
      },
    ],
    videoUrl: 'https://www.youtube.com/embed/CrF_hRZt3M4',
  },
  {
    id: 5,
    title: 'v1.4',
    date: '10 SEP 2026',
    icon: 'point_of_sale',
    status: true,
    statusName: 'Publicado',
    statusColor: 'primary',
    statusIcon: 'check_circle',
    content: 'v1.4',
    isNew: true,
    features: [
      'Generación de ventas utilizando productos variantes.',
      'Selección del tipo de venta, cliente, canal, origen y almacén.',
      'Selección de la categoría de precios para la operación.',
      'Visualización de las variantes disponibles según el modelo de producto seleccionado.',
      'Filtro de productos variantes por series asociadas al modelo.',
      'Selección de variantes específicas y registro de cantidades para la venta.',
      'Agregación al carrito únicamente de las variantes seleccionadas.',
      'Revisión de productos, cantidades y precios antes de confirmar la venta.',
      'Selección del método de pago y asignación de caja o banco.',
    ],
    modules: [
      {
        name: 'Ventas',
        tooltip: 'Generación y gestión de ventas',
        icon: 'point_of_sale',
      },
      {
        name: 'Productos',
        tooltip: 'Selección de modelos y productos variantes',
        icon: 'inventory_2',
      },
      {
        name: 'Series',
        tooltip: 'Filtro de productos variantes por serie',
        icon: 'filter_alt',
      },
      {
        name: 'Caja y bancos',
        tooltip: 'Gestión de pagos y asignación de operaciones',
        icon: 'account_balance',
      },
    ],
    videoUrl: 'https://www.youtube.com/embed/i90Qgw16qYc',
  },
  {
    id: 6,
    title: 'v1.5',
    date: '10 SEP 2026',
    icon: 'local_shipping',
    status: true,
    statusName: 'Publicado',
    statusColor: 'primary',
    statusIcon: 'check_circle',
    content: 'v1.5',
    isNew: true,
    features: [
      'Registro de movimientos de productos entre un almacén de origen y un almacén de destino.',
      'Consulta y filtrado de movimientos por almacén.',
      'Selección de un almacén de origen y un almacén de destino para cada movimiento.',
      'Visualización del stock disponible en el almacén de origen y en el almacén de destino.',
      'Selección de productos variantes según el modelo de producto.',
      'Filtro de productos variantes por series asociadas al modelo.',
      'Registro de cantidades específicas para cada producto variante.',
      'Ingreso al movimiento únicamente de las variantes cuya cantidad sea mayor que cero.',
      'Revisión de los productos y cantidades antes de procesar el movimiento.',
      'Autorización y confirmación del movimiento entre almacenes.',
      'Actualización de las existencias de los almacenes después de autorizar la operación.',
    ],
    modules: [
      {
        name: 'Movimientos',
        tooltip: 'Gestión de movimientos entre almacenes',
        icon: 'local_shipping',
      },
      {
        name: 'Almacenes',
        tooltip: 'Selección de almacenes de origen y destino',
        icon: 'warehouse',
      },
      {
        name: 'Productos',
        tooltip: 'Selección de modelos y productos variantes',
        icon: 'inventory_2',
      },
      {
        name: 'Series',
        tooltip: 'Filtro de productos variantes por serie',
        icon: 'filter_alt',
      },
    ],
    videoUrl: 'https://www.youtube.com/embed/ZiIldHIj-F8',
  },
]
