// Configuración de versiones del sistema
export const versionesConfig = [
  {
    id: 1,
    title: 'v1.0',
    date: '14 ENE 2026',
    icon: 'rocket_launch',
    status: true,
    statusName: 'Publicado',
    statusColor: 'primary',
    statusIcon: 'check_circle',
    content: 'v1.0',
    isNew: false,
    features: [
      'Filtros avanzados en tablas principales (Fecha, Numéricos, Texto).',
      'Botones de acceso rápido en cabeceras de columnas.',
      'Optimización de rendimiento en carga de reportes.',
      'Nueva interfaz de usuario más limpia y amigable.',
    ],
    modules: [
      { name: 'Compras', tooltip: 'Reporte de Compras Desglosado', icon: 'shopping_cart' },
      { name: 'Stock', tooltip: 'Reporte individual de productos', icon: 'inventory_2' },
      { name: 'Ventas', tooltip: 'Ventas y Contingencias', icon: 'point_of_sale' },
      { name: 'Anulaciones', tooltip: 'Gestión de devoluciones', icon: 'remove_shopping_cart' },
    ],
    videoUrl: 'https://www.youtube.com/embed/bvTBbz2AdFQ?si=RhtXAXCnJsx5AQFI',
  },
  {
    id: 2,
    title: 'v1.1',
    date: '03 FEB 2026',
    icon: 'inventory',
    status: true,
    statusName: 'Publicado',
    statusColor: 'primary',
    statusIcon: 'check_circle',
    content: 'v1.1',
    isNew: true,
    features: [
      'Select de filtro sincronizado entre Tabla y Pedidos Movimiento.',
      'Checkboxes para envío masivo de pedidos con mismo destino.',
      'Validación automática de destinos incompatibles.',
      'Actualización automática de tabla sin recargar página.',
      'Visualización de productos acumulados antes de enviar.',
      'Comentarios múltiples separados por punto y coma en Descripción.',
      'Generación de PDF del pedido para reporte físico o digital.',
    ],
    modules: [
      { name: 'Movimientos', tooltip: 'Gestión de movimientos de almacén', icon: 'local_shipping' },
      { name: 'Pedidos', tooltip: 'Pedidos de movimiento entre almacenes', icon: 'shopping_bag' },
      { name: 'Reportes', tooltip: 'Generación de PDF de pedidos', icon: 'picture_as_pdf' },
      { name: 'Almacenes', tooltip: 'Sincronización de almacenes', icon: 'warehouse' },
    ],
    videoUrl: 'https://www.youtube.com/embed/v7wT0NREf-0?si=aHJpH-SFyANYhYz9', // Reemplazar con el ID real del video
  },
  {
    id: 3,
    title: 'Próximamente',
    date: 'En desarrollo',
    icon: 'construction',
    status: true,
    statusName: 'En Progreso',
    statusColor: 'orange',
    statusIcon: 'engineering',
    content: 'future',
    isNew: false,
  },
]
