const contenidousuario = JSON.parse(localStorage.getItem('yofinanciero'))
let idempresa
let idusuario
if (contenidousuario) {
  idempresa = contenidousuario[0]?.empresa?.idempresa
  idusuario = contenidousuario[0]?.idusuario
} else {
  console.log('Los elementos no existen en localStorage')
  window.location.assign('../../vapp/')
}

export const asignarUsuarioF = {
  tableHeader: {
    columns: ['N°', 'Usuario', 'Cargo', 'Almacén', 'Opciones'],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verAA',
      name: 'ver',
      value: 'registrarResponsable',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaTA',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'select',
      label: 'usuario',
      titulo: 'Usuarios*',
      type: 'select',
      id: 'usuarioAA',
      name: 'usuario',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'Cargo',
      titulo: 'Cargo*',
      type: 'text',
      id: 'cargoAA',
      name: 'cargo',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      modelo: 'select',
      label: 'almacen',
      titulo: 'Almacén*',
      type: 'select',
      id: 'almacenAA',
      name: 'almacen',
      placeholder: '',
      required: false,
      disabled: false,
    },
  ],
}

export const asignarPuntoVentaF = {
  tableHeader: {
    columns: ['N°', 'Usuario', 'Cargo', 'Almacén', 'Puntos Venta', 'Opciones'],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verRPV',
      name: 'ver',
      value: 'registrarResponsablePuntoVenta',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaRPV',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'select',
      label: 'usuario',
      titulo: 'Resposable*',
      type: 'select',
      id: 'idresponsableRPV',
      name: 'idresponsable',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'select',
      label: 'almacen',
      titulo: 'Almacén*',
      type: 'select',
      id: 'almacenRPV',
      name: 'idalmacen',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      modelo: 'select',
      label: 'puntoventa',
      titulo: 'Punto de venta*',
      type: 'select',
      id: 'idpuntoventaRPV',
      name: 'idpuntoventa',
      placeholder: '',
      required: false,
      disabled: false,
    },
  ],
}

export const tipoAlmacenF = {
  tableHeader: {
    columns: ['N°', 'Tipos', 'Descripción', 'Estado', 'Opciones'],
  },
  nroColumns: 2,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verTA',
      name: 'ver',
      value: 'registrarTipoAlmacen',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaTA',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombre-tipo-almacen',
      titulo: 'Tipo de almacén*',
      type: 'text',
      id: 'nombreTA',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'descripcion-tipo-almacén',
      titulo: 'Descripción del tipo de almacén*',
      type: 'text',
      id: 'descripcionTA',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const categoriaProductoF = {
  tableHeader: {
    columns: ['N°', 'Nombre', 'Descripción', 'Estado', 'Opciones'],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verCP',
      name: 'ver',
      value: 'registrarCategoriaProducto',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaCP',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'nombre-categoria-producto',
      titulo: 'Categoría del producto*',
      type: 'text',
      id: 'nombreCP',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'descripcion-categoria-producto',
      titulo: 'Descripción de la categoría del producto*',
      type: 'text',
      id: 'descripcionCP',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'select',
      label: 'tipo',
      titulo: 'Tipo de registro*',
      type: 'select',
      id: 'tipoCP',
      name: 'tipoCP',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'select',
      label: 'idpadreCP',
      titulo: 'Categoría*',
      type: 'select',
      id: 'idpadreCP',
      name: 'idpadreCP',
      placeholder: '',
      required: false,
      disabled: false,
    },
  ],
}

export const estadoProductoF = {
  tableHeader: {
    columns: ['N°', 'Estado', 'Descripción', 'Estado', 'Opciones'],
  },
  nroColumns: 2,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verEP',
      name: 'ver',
      value: 'registrarEstadoProducto',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaEP',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombre-estado-producto',
      titulo: 'Estado del producto*',
      type: 'text',
      id: 'nombreEP',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'descripcion-estado-producto',
      titulo: 'Descripción del estado del producto*',
      type: 'text',
      id: 'descripcionEP',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const unidadProductoF = {
  tableHeader: {
    columns: ['N°', 'Unidad', 'Descripción', 'Estado', 'Opciones'],
  },
  nroColumns: 2,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verUP',
      name: 'ver',
      value: 'registrarUnidadProducto',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaUP',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombre-unidad-producto',
      titulo: 'Unidad del producto*',
      type: 'text',
      id: 'nombreUP',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'descripcion-unidad-producto',
      titulo: 'Descripción de la unidad del producto*',
      type: 'text',
      id: 'descripcionUP',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const caracteristicaProductoF = {
  tableHeader: {
    columns: ['N°', 'Característica', 'Descripción', 'Estado', 'Opciones'],
  },
  nroColumns: 2,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verCAP',
      name: 'ver',
      value: 'registrarCaracteristicaProducto',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaCAP',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombre-caracteristica-producto',
      titulo: 'Característica del producto*',
      type: 'text',
      id: 'nombreCAP',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'descripcion-caracteristica-producto',
      titulo: 'Descripción de la característica del producto*',
      type: 'text',
      id: 'descripcionCAP',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const divisasF = {
  true: {
    tableHeader: {
      columns: ['N°', 'Divisa', 'Tipo', 'Moneda (SIN)', 'Estado', 'Opciones'],
    },
    nroColumns: 3,
    fields: [
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'verDI',
        name: 'ver',
        value: 'registrarDivisa',
        required: true,
        disabled: false,
      },
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'idempresaDI',
        name: 'idempresa',
        value: idempresa,
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'nombre-divisa',
        titulo: 'Nombre de divisa*',
        type: 'text',
        id: 'nombreDI',
        name: 'nombre',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'simbolo-divisa',
        titulo: 'Símbolo de la divisa*',
        type: 'text',
        id: 'tipoDI',
        name: 'tipo',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'select2',
        label: 'moneda-sin',
        titulo: 'Modena (SIN)*',
        type: 'text',
        id: 'divisafac',
        name: 'monedasinfac',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'monedasinDF',
        name: 'monedasin',
        placeholder: '',
        required: true,
        disabled: false,
      },
    ],
  },
  false: {
    tableHeader: {
      columns: ['N°', 'Divisa', 'Tipo', 'Estado', 'Opciones'],
    },
    nroColumns: 2,
    fields: [
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'verDI',
        name: 'ver',
        value: 'registrarDivisa',
        required: true,
        disabled: false,
      },
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'idempresaDI',
        name: 'idempresa',
        value: idempresa,
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'nombre-divisa',
        titulo: 'Nombre de la divisa*',
        type: 'text',
        id: 'nombreDI',
        name: 'nombre',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'simbolo-divisa',
        titulo: 'Simbolo de la divisa*',
        type: 'text',
        id: 'tipoDI',
        name: 'tipo',
        placeholder: '',
        required: true,
        disabled: false,
      },
    ],
  },
}

export const TipoClienteF = {
  tableHeader: {
    columns: ['N°', 'Tipo', 'Descripción', 'Estado', 'Opciones'],
  },
  nroColumns: 2,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verTC',
      name: 'ver',
      value: 'registrarTipoCLiente',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaTC',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombre-tipo-cliente',
      titulo: 'Tipo cliente*',
      type: 'text',
      id: 'tipoTC',
      name: 'tipo',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'descripcion-tipo-cliente',
      titulo: 'Descripción del tipo cliente*',
      type: 'text',
      id: 'descripcionTC',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const leyendaProformaF = {
  tableHeader: {
    columns: ['N°', 'Leyenda', 'Estado', 'Opciones'],
  },
  nroColumns: 1,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verLC',
      name: 'ver',
      value: 'registrarLeyendaCotizacion',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaLC',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'texto-leyenda',
      titulo: 'Leyenda de la cotización*',
      type: 'text',
      id: 'textoLC',
      name: 'texto',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const canalVentaF = {
  tableHeader: {
    columns: ['N°', 'Canal', 'Descripción', 'Estado', 'Opciones'],
  },
  nroColumns: 2,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verCV',
      name: 'ver',
      value: 'registrarCanalVenta',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaCV',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombre-canal-venta',
      titulo: 'Nombre del canal de venta*',
      type: 'text',
      id: 'canalCV',
      name: 'canal',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'descripcion-canal-venta',
      titulo: 'Descripción del canal de venta*',
      type: 'text',
      id: 'descripcionCV',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const costoUnitarioF = {
  tableHeader: {
    columns: ['N°', 'Código', 'Descripción', 'Costo', 'Opciones'],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verPB',
      name: 'ver',
      value: 'registrarPrecioBase',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idproductoalmacenPB',
      name: 'idproductoalmacen',
      value: 0,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombre-Producto',
      titulo: 'Descripción del producto*',
      type: 'text',
      id: 'descripcionPB',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      modelo: 'inputgroup',
      label: 'precio-base',
      titulo: 'Costo unitario actual del producto*',
      type: 'text',
      id: 'precioactualPB',
      name: 'precioactual',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      modelo: 'inputgroup',
      label: 'nuevo-precio-base',
      titulo: 'Nuevo costo unitario del producto*',
      type: 'text',
      id: 'precionuevoPB',
      name: 'precio',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const categoriaPrecioF = {
  tableHeader: {
    columns: ['N°', 'Categoría', 'Porcentaje', 'Estado', 'Opciones'],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verCPR',
      name: 'ver',
      value: 'registrarCategoriaPrecio',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaCPR',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombreCPR',
      titulo: 'Categoría de precio*',
      type: 'text',
      id: 'nombreCPR',
      name: 'tipo',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'porcentajeCPR',
      titulo: 'Porcentaje incremento al costó unitario*',
      type: 'text',
      id: 'porcentajeCPR',
      name: 'porcentaje',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'select',
      label: 'idalmacenCPR',
      titulo: 'Almacén*',
      type: 'select',
      id: 'idalmacenCPR',
      name: 'idalmacen',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const precioSugeridoF = {
  tableHeader: {
    columns: ['N°', 'Código', 'Descripción', 'Precio', 'Opciones'],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verPS',
      name: 'ver',
      value: 'editarPrecioSugerido',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaPS',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombrePS',
      titulo: 'Descripción del producto',
      type: 'text',
      id: 'nombrePS',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      modelo: 'inputgroup',
      label: 'preciosugeridoPS',
      titulo: 'Actual precio sugerido',
      type: 'text',
      id: 'preciosugeridoPS',
      name: 'preciosugeridoPS',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      modelo: 'inputgroup',
      label: 'nuevopreciosugeridoPS',
      titulo: 'Nuevo precio sugerido*',
      type: 'text',
      id: 'nuevopreciosugeridoPS',
      name: 'precio',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const leyendaFacturaF = {
  tableHeader: {
    columns: ['N°', 'Nombre', 'Descripción(SIN)', 'Estado', 'Opciones'],
  },
  nroColumns: 2,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verLF',
      name: 'ver',
      value: 'registrarLeyendaFactura',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaLF',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombreLF',
      titulo: 'Nombre de la leyenda*',
      type: 'text',
      id: 'nombreLF',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'select2',
      label: 'descripcionLF',
      titulo: 'Leyenda(SIN)',
      type: 'text',
      id: 'descripcionLF',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'codigoSINLF',
      name: 'codigosin',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const metodopagoFacturaF = {
  tableHeader: {
    columns: ['N°', 'Método de pago', 'Descripción(SIN)', 'Estado', 'Opciones'],
  },
  nroColumns: 2,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verMPF',
      name: 'ver',
      value: 'registrarMetodoPagoFactura',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaMPF',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombreLF',
      titulo: 'Nombre del método de pago*',
      type: 'text',
      id: 'nombreMPF',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'select2',
      label: 'descripcionMPF',
      titulo: 'Método de pago (SIN)*',
      type: 'text',
      id: 'descripcionMPF',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'codigoSINMPF',
      name: 'codigosin',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const parametrosF = {
  tableHeader: {
    columns: ['N°', 'Parámetro', 'Valor', 'Nombre color', 'Color', 'Opciones'],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verPO',
      name: 'ver',
      value: 'registrarParametro',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaPO',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombrePS',
      titulo: 'Parámetro*',
      type: 'text',
      id: 'nombrePO',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'preciosugeridoPS',
      titulo: 'Valor*',
      type: 'text',
      id: 'valorPO',
      name: 'valor',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'select',
      label: 'nuevopreciosugeridoPS',
      titulo: 'Color*',
      type: 'select',
      id: 'colorPO',
      name: 'color',
      placeholder: '',
      required: true,
      disabled: false,
    } /*,
        {
            modelo: "select",
            label: "nuevopreciosugeridoPS",
            titulo: "tipo*",
            type: "select",
            id: "colorPO",
            name: "color",
            placeholder: "",
            required: true,
            disabled: false
        }*/,
  ],
}

export const almacenF = {
  tableHeader: {
    columns: [
      'N°',
      'Nombre',
      'Dirección',
      'Teléfono',
      'Email',
      'Tipo almacén',
      'Stock min',
      'Stock max',
      'Sucursal',
      'Estado',
      'Opciones',
    ],
  },

  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verA',
      name: 'ver',
      value: 'registrarAlmacen',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaA',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'nombre-Almacen',
      titulo: 'Nombre*',
      type: 'text',
      id: 'nombreA',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'direccion-almacen',
      titulo: 'Dirección*',
      type: 'text',
      id: 'direccionA',
      name: 'direccion',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'telefono-almacen',
      titulo: 'Teléfono*',
      type: 'text',
      id: 'telefonoA',
      name: 'telefono',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'email-almacen',
      titulo: 'Email',
      type: 'email',
      id: 'emailA',
      name: 'email',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      modelo: 'select',
      label: 'tipoalmacen-almacen',
      titulo: 'Tipo almacén*',
      type: 'select',
      id: 'tipoalmacenA',
      name: 'tipoalmacen',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'stockmin-almacen',
      titulo: 'Stock mínimo*',
      type: 'text',
      id: 'stockminA',
      name: 'stockmin',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'text',
      label: 'stockmax-almacen',
      titulo: 'Stock máximo*',
      type: 'text',
      id: 'stockmaxA',
      name: 'stockmax',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'select',
      label: 'sucursal-almacen',
      titulo: 'Sucursal*',
      type: 'select',
      id: 'sucursalA',
      name: 'sucursal',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const productoF = {
  true: {
    tableHeader: {
      columns: [
        'N°',
        'Código',
        'Nombre',
        'Descripción',
        'Categoría',
        'Sub categoría',
        'Código barra',
        'Característica',
        'Estado',
        'Unidad',
        'Otras características',
        'Fecha creación.',
        'Producto (SIN)',
        'Unidad (SIN)',
        'Código nandina',
        'Imagen',
        'Opciones',
      ],
    },
    nroColumns: 3,
    fields: [
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'verPRO',
        name: 'ver',
        value: 'registrarProducto',
        required: true,
        disabled: false,
      },
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'idempresaPRO',
        name: 'idempresa',
        value: idempresa,
        required: true,
        disabled: false,
      },
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'codigosinPRO',
        name: 'codigosin',
        value: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'codigoactividadPRO',
        name: 'codigoactividad',
        value: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'unidadsinPRO',
        name: 'unidadsin',
        value: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'codigoProducto',
        titulo: 'Código*',
        type: 'text',
        id: 'codigoPRO',
        name: 'codigo',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'nombreProducto',
        titulo: 'Nombre*',
        type: 'text',
        id: 'nombrePRO',
        name: 'nombre',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'descripcionProducto',
        titulo: 'Descripción*',
        type: 'text',
        id: 'descripcionPRO',
        name: 'descripcion',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'codBarrasProducto',
        titulo: 'Código barras',
        type: 'text',
        id: 'codigobarrasPRO',
        name: 'codigobarras',
        placeholder: '',
        required: false,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'categoriaProducto',
        titulo: 'Categorías*',
        type: 'select',
        id: 'categoriasPRO',
        name: '',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'subcategoriaProducto',
        titulo: 'Sub categorías*',
        type: 'select',
        id: 'subcategoriasPRO',
        name: '',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'caracteristicaProducto',
        titulo: 'Caracteristicas*',
        type: 'select',
        id: 'medidaPRO',
        name: 'medida',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'estadoProducto',
        titulo: 'Estado*',
        type: 'select',
        id: 'estadosproductoPRO',
        name: 'estadoproductos',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'unidadProducto',
        titulo: 'Unidad*',
        type: 'select',
        id: 'unidadPRO',
        name: 'unidad',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'otraCaracteristica',
        titulo: 'Otras características',
        type: 'text',
        id: 'caracteristicaPRO',
        name: 'caracteristica',
        placeholder: '',
        required: false,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'imagenproducto',
        titulo: 'Imagen del producto',
        type: 'file',
        id: 'imagenPRO',
        name: 'imagen',
        placeholder: '',
        required: false,
        disabled: false,
      },
      {
        modelo: 'select2',
        label: 'productosin',
        titulo: 'Producto SIN',
        type: 'text',
        id: 'productosinTextPRO',
        name: 'productosinPRO',
        placeholder: '',
        required: false,
        disabled: false,
      },
      {
        modelo: 'select2',
        label: 'unidadsin',
        titulo: 'Unidad SIN',
        type: 'text',
        id: 'unidadsinTextPRO',
        name: 'unidadsinPRO',
        placeholder: '',
        required: false,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'codigonandina',
        titulo: 'Código nandina',
        type: 'text',
        id: 'codigonandinaPRO',
        name: 'codigoNandina',
        placeholder: '',
        required: false,
        disabled: false,
      },
    ],
  },
  false: {
    tableHeader: {
      columns: [
        'N°',
        'Cod.',
        'Nombre',
        'Descripción',
        'Categoría',
        'Sub Categorías',
        'Cod.Barra',
        'Caract.',
        'Estado',
        'Unidad',
        'Otras caract.',
        'Fecha',
        'Imagen',
        'Opciones',
      ],
    },
    nroColumns: 3,
    fields: [
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'verPRO',
        name: 'ver',
        value: 'registrarProducto',
        required: true,
        disabled: false,
      },
      {
        modelo: 'hidden',
        label: '',
        titulo: '',
        type: 'hidden',
        id: 'idempresaPRO',
        name: 'idempresa',
        value: idempresa,
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'codigoProducto',
        titulo: 'Cod. Producto*',
        type: 'text',
        id: 'codigoPRO',
        name: 'codigo',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'nombreProducto',
        titulo: 'Nombre del Producto*',
        type: 'text',
        id: 'nombrePRO',
        name: 'nombre',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'descripcionProducto',
        titulo: 'Descripción*',
        type: 'text',
        id: 'descripcionPRO',
        name: 'descripcion',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'codBarrasProducto',
        titulo: 'Cod. de Barras',
        type: 'text',
        id: 'codigobarrasPRO',
        name: 'codigobarras',
        placeholder: '',
        required: false,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'categoriaProducto',
        titulo: 'Categorías*',
        type: 'select',
        id: 'categoriasPRO',
        name: '',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'subcategoriaProducto',
        titulo: 'Sub categorías*',
        type: 'select',
        id: 'subcategoriasPRO',
        name: '',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'caracteristicaProducto',
        titulo: 'Caracteristica*',
        type: 'select',
        id: 'medidaPRO',
        name: 'medida',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'estadoProducto',
        titulo: 'Estados del Producto*',
        type: 'select',
        id: 'estadosproductoPRO',
        name: 'estadoproductos',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'select',
        label: 'unidadProducto',
        titulo: 'Unidad*',
        type: 'select',
        id: 'unidadPRO',
        name: 'unidad',
        placeholder: '',
        required: true,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'otraCaracteristica',
        titulo: 'Otras.Caract.',
        type: 'text',
        id: 'caracteristicaPRO',
        name: 'caracteristica',
        placeholder: '',
        required: false,
        disabled: false,
      },
      {
        modelo: 'text',
        label: 'imagenproducto',
        titulo: 'Imagen del Producto',
        type: 'file',
        id: 'imagenPRO',
        name: '',
        placeholder: '',
        required: false,
        disabled: false,
      },
    ],
  },
}

export const productoAlmacenF = {
  tableHeader: {
    columns: [
      'N°',
      'Cod.',
      'Nombre',
      'Descripción',
      'Uni.',
      'Caract.',
      'Est.Producto',
      'Stock',
      'Stock.Min',
      'Stock.Max',
      'Estado',
      'Opciones',
    ],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verCPR',
      name: 'ver',
      value: 'registrarProductoAlmacen',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idproductoalmacen',
      name: 'idproductoalmacen',
      value: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'paisPA',
      titulo: 'Pais de Origen*',
      type: 'text',
      id: 'detallePA',
      name: 'detalle',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'stockminPA',
      titulo: 'Stock Minimo*',
      type: 'text',
      id: 'stockminPA',
      name: 'stockmin',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'stockmaxPA',
      titulo: 'Stock Maximo*',
      type: 'text',
      id: 'stockmaxPA',
      name: 'stockmax',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const movimientoF = {
  tableHeader: {
    columns: [
      'N°',
      'Fecha',
      'Almacén origen',
      'Almacén destino',
      'Descripción',
      'Autorización',
      'Detalle',
      'Opciones',
    ],
  },
  nroColumns: 2,
  tableHeaderForm: {
    columns: ['N°', 'Código', 'Descripción', 'Cantidad', 'Opciones'],
  },
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verMOV',
      name: 'ver',
      value: 'registrarMovimiento',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idMOV',
      name: 'id',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idusuario',
      name: 'idusuario',
      value: idusuario,
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'text',
      label: 'fechaMOV',
      titulo: 'Fecha*',
      type: 'date',
      id: 'fechaMOV',
      name: 'fecha',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'text',
      label: 'descripcionMOV',
      titulo: 'Descripción*',
      type: 'text',
      id: 'descripcionMOV',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'select',
      label: 'almacenorigenMOV',
      titulo: 'Almacén Origen*',
      type: 'select',
      id: 'almacenorigenMOV',
      name: 'almacenorigen',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'select',
      label: 'almacendestinoMOV',
      titulo: 'Almacén Destino*',
      type: 'select',
      id: 'almacendestinoMOV',
      name: 'almacendestino',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
  fields2: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verDMOV',
      name: 'ver',
      value: 'registrarDetalleMovimiento',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idmovimientoMOV',
      name: 'idmovimiento',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idproductoalmacenDMOV',
      name: 'idproductoalmacen',
      value: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select2',
      label: 'productosDMOV',
      titulo: 'Producto*',
      type: 'text',
      id: 'productosdisponiblesMOV',
      name: 'productos',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'stockaoDMOV',
      titulo: 'Stock origen*',
      type: 'text',
      id: 'stockoDMOV',
      name: '',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'stockdDMOV',
      titulo: 'Stock destino*',
      type: 'text',
      id: 'stockdDMOV',
      name: '',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'cantidaDMOV',
      titulo: 'Cantidad*',
      type: 'text',
      id: 'cantidadDMOV',
      name: 'cantidad',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const proveedorF = {
  tableHeader: {
    columns: [
      'N°',
      'Nombre.',
      'Código',
      'NIT',
      'Detalle',
      'Dirección',
      'Email',
      'Teléfono',
      'Movil',
      'Ciudad',
      'Zona',
      'País',
      'Web',
      'Contacto',
      'Opciones',
    ],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verPRVE',
      name: 'ver',
      value: 'registrarProveedor',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaPRVE',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'nombrePRVE',
      titulo: 'Nombre Proveedor*',
      type: 'text',
      id: 'nombrePRVE',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'codigoPRVE',
      titulo: 'Código*',
      type: 'text',
      id: 'codigoPRVE',
      name: 'codigo',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'nitPRVE',
      titulo: 'NIT*',
      type: 'text',
      id: 'nitPRVE',
      name: 'nit',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'detallePRVE',
      titulo: 'Detalle',
      type: 'text',
      id: 'detallePRVE',
      name: 'detalle',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'emailPRVE',
      titulo: 'Email',
      type: 'text',
      id: 'emailPRVE',
      name: 'email',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'direccionPRVE',
      titulo: 'Dirección*',
      type: 'text',
      id: 'direccionPRVE',
      name: 'direccion',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'telefonoPRVE',
      titulo: 'Teléfono',
      type: 'text',
      id: 'telefonoPRVE',
      name: 'telefono',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'movilPRVE',
      titulo: 'Movil*',
      type: 'text',
      id: 'movilPRVE',
      name: 'movil',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'paisPRVE',
      titulo: 'País*',
      type: 'text',
      id: 'paisPRVE',
      name: 'pais',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'ciudadPRVE',
      titulo: 'Ciudad*',
      type: 'text',
      id: 'ciudadPRVE',
      name: 'ciudad',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'zonaPRVE',
      titulo: 'zona',
      type: 'text',
      id: 'zonaPRVE',
      name: 'zona',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'webPRVE',
      titulo: 'Página Web',
      type: 'text',
      id: 'webPRVE',
      name: 'web',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'contactoPRVE',
      titulo: 'Contacto',
      type: 'text',
      id: 'contactoPRVE',
      name: 'contacto',
      placeholder: '',
      required: false,
      disabled: false,
    },
  ],
}

export const pedidosF = {
  tableHeader: {
    columns: [
      'N°',
      'Fecha',
      'Almacén origen',
      'Almacén destino',
      'Código',
      'Tipo',
      'Observación',
      'Autorización',
      'Estado',
      'Detalle',
      'Opciones',
    ],
  },
  nroColumns: 2,
  tableHeaderForm: {
    columns: ['N°', 'Código', 'Descripción', 'Cantidad', 'Opciones'],
  },
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verPED',
      name: 'ver',
      value: 'registrarPedido',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idPED',
      name: 'id',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idalmacendestinoPED',
      name: 'almacendestino',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaPED',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idusuarioPED',
      name: 'idusuario',
      value: idusuario,
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'text',
      label: 'fechaPED',
      titulo: 'Fecha*',
      type: 'date',
      id: 'fechaPED',
      name: 'fecha',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'select',
      label: 'tipoPED',
      titulo: 'Tipo de Pedido*',
      type: 'select',
      id: 'tipoPED',
      name: 'tipo',
      placeholder: '',
      required: true,
      disabled: false,
    },

    {
      tamaño: 6,
      modelo: 'select',
      label: 'almacenorigenPED',
      titulo: 'Almacén Destino*',
      type: 'select',
      id: 'almacenorigenPED',
      name: 'almacenorigen',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'select',
      label: 'almacendestinoPED',
      titulo: 'Almacén Origen*',
      type: 'select',
      id: 'almacendestinoPED',
      name: '',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'text',
      label: 'observacionPED',
      titulo: 'Observación*',
      type: 'text',
      id: 'observacionPED',
      name: 'observacion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
  fields2: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verPEDD',
      name: 'ver',
      value: 'registrarDetallePedido',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idpedidoPEDD',
      name: 'idpedido',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idproductoalmacenPEDD',
      name: 'idproductoalmacen',
      value: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'select2',
      label: 'productosPEDD',
      titulo: 'Producto*',
      type: 'text',
      id: 'productosPEDD',
      name: 'productos',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'stockPEDD',
      titulo: 'Stock Actual*',
      type: 'text',
      id: 'stockPEDD',
      name: '',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'cantidaPEDD',
      titulo: 'Cantidad*',
      type: 'text',
      id: 'cantidadPEDD',
      name: 'cantidad',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const ComprasF = {
  tableHeader: {
    columns: [
      'N°',
      'Fecha',
      'Proveedor',
      'Nombre lote',
      'Código',
      'N° Factura',
      'Tipo compra',
      'Total compra',
      'Autorización',
      'Detalle',
      'Opciones',
    ],
  },
  nroColumns: 2,
  tableHeaderForm: {
    columns: ['N°', 'Código', 'Descripción', 'Precio', 'Cantidad', 'Opciones'],
  },
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verCOM',
      name: 'ver',
      value: 'registrarCompra',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idCOM',
      name: 'id',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idalmaCOM',
      name: 'almacen',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idpedCOM',
      name: 'pedido',
      value: 0,
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idusuarioCOM',
      name: 'idusuario',
      value: idusuario,
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select',
      label: 'opcionPCOM',
      titulo: 'Tipo registro*',
      type: 'select',
      id: 'opcionPCOM',
      name: '',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select',
      label: 'idalmacenCOM',
      titulo: 'Almacén*',
      type: 'select',
      id: 'idalmacenCOM',
      name: '',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select',
      label: 'pedidoCOM',
      titulo: 'Pedido*',
      type: 'select',
      id: 'pedidoCOM',
      name: '',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'nombreCOM',
      titulo: 'Nombre*',
      type: 'text',
      id: 'nombreCOM',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'codigoCOM',
      titulo: 'Código*',
      type: 'text',
      id: 'codigoCOM',
      name: 'codigo',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select',
      label: 'proveedorCOM',
      titulo: 'Proveedor*',
      type: 'select',
      id: 'proveedorCOM',
      name: 'proveedor',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'facturaCOM',
      titulo: 'Nro Factura',
      type: 'text',
      id: 'facturaCOM',
      name: 'factura',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select',
      label: 'tipocompraCOM',
      titulo: 'Tipo de Compra*',
      type: 'select',
      id: 'tipocompraCOM',
      name: 'tipocompra',
      placeholder: '',
      required: false,
      disabled: false,
    },
  ],
  fields2: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verCOMD',
      name: 'ver',
      value: 'registrarDetalleCompra',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idingresoCOMD',
      name: 'idingreso',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idproductoalmacenCOMD',
      name: 'idproductoalmacen',
      value: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select2',
      label: 'productosPEDD',
      titulo: 'Producto*',
      type: 'text',
      id: 'productosCOMD',
      name: 'productos',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'stockCOMD',
      titulo: 'Stock actual*',
      type: 'text',
      id: 'stockCOMD',
      name: '',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      tamaño: 2,
      modelo: 'inputgroup',
      label: 'precioCOMD',
      titulo: 'Precio*',
      type: 'text',
      id: 'precioCOMD',
      name: 'precio',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'cantidaCOMD',
      titulo: 'Cantidad*',
      type: 'text',
      id: 'cantidadCOMD',
      name: 'cantidad',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const clientesF = {
  tableHeader: {
    columns: [
      'N°',
      'Razón Social',
      'Nombre Comercial',
      'Codigo',
      'Tipo',
      'Canal Venta',
      'Tipo.Doc',
      'Nro.Doc',
      'Detalle',
      'Dirección',
      'Email',
      'Telefono',
      'Movil',
      'Ciudad',
      'Zona',
      'Pais',
      'Web',
      'Contacto',
      'Opciones',
    ],
  },
  tableHeaderForm: {
    columns: ['N°', 'Nombre', 'telefono', 'Dirección', 'Opciones'],
  },
  nroColumns: 3,
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verCLI',
      name: 'ver',
      value: 'registrarCliente',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idempresaCLI',
      name: 'idempresa',
      value: idempresa,
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'nombreCLI',
      titulo: 'Razon Social*',
      type: 'text',
      id: 'nombreCLI',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'nombrecomercialCLI',
      titulo: 'Nombre Comercial*',
      type: 'text',
      id: 'nombrecomercialCLI',
      name: 'nombrecomercial',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'select',
      label: 'tipoclienteCLI',
      titulo: 'Tipo de Cliente*',
      type: 'select',
      id: 'tipoclienteCLI',
      name: 'tipocliente',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'select',
      label: 'canalventaCLI',
      titulo: 'Canal de venta*',
      type: 'select',
      id: 'canalventaCLI',
      name: 'canalventa',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'select',
      label: 'tipodocumentoCLI',
      titulo: 'Tipo de Documento*',
      type: 'select',
      id: 'tipodocumentoCLI',
      name: 'tipodocumento',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'nrodocCLI',
      titulo: 'Nro De Documento*',
      type: 'text',
      id: 'nrodocCLI',
      name: 'nrodocumento',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'emailCLI',
      titulo: 'Email',
      type: 'email',
      id: 'emailCLI',
      name: 'email',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'direccionCLI',
      titulo: 'Dirección',
      type: 'text',
      id: 'direccionCLI',
      name: 'direccion',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'telefonoCLI',
      titulo: 'Telefono',
      type: 'text',
      id: 'telefonoCLI',
      name: 'telefono',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'movilCLI',
      titulo: 'Movil*',
      type: 'text',
      id: 'movilCLI',
      name: 'movil',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'paisCLI',
      titulo: 'Pais*',
      type: 'text',
      id: 'paisCLI',
      name: 'pais',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'ciudadCLI',
      titulo: 'Ciudad*',
      type: 'text',
      id: 'ciudadCLI',
      name: 'ciudad',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'zonaCLI',
      titulo: 'zona',
      type: 'text',
      id: 'zonaCLI',
      name: 'zona',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'webCLI',
      titulo: 'Pagina Web',
      type: 'text',
      id: 'webCLI',
      name: 'web',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'contactoCLI',
      titulo: 'Contacto',
      type: 'text',
      id: 'contactoCLI',
      name: 'contacto',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'detalleCLI',
      titulo: 'Detalle',
      type: 'text',
      id: 'detalleCLI',
      name: 'detalle',
      placeholder: '',
      required: false,
      disabled: false,
    },
  ],
  fields2: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verSUC',
      name: 'ver',
      value: 'registrarSucursal',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idclienteCLIS',
      name: 'idcliente',
      value: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'nombreSUC',
      titulo: 'Nombre*',
      type: 'text',
      id: 'nombreSUC',
      name: 'nombre',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'telefonoSUC',
      titulo: 'Telefono',
      type: 'text',
      id: 'telefonoSUC',
      name: 'telefono',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'direccionSUC',
      titulo: 'Dirección',
      type: 'text',
      id: 'direccionSUC',
      name: 'direccion',
      placeholder: '',
      required: false,
      disabled: false,
    },
  ],
}

export const inventarioExternoF = {
  tableHeader: {
    columns: [
      'N°',
      'Fecha',
      'Almacén',
      'Cliente',
      'Sucursal',
      'Observación',
      'Imagen',
      'Autorización',
      'Detalle',
      'Opciones',
    ],
  },
  nroColumns: 2,
  tableHeaderForm: {
    columns: ['N°', 'Código', 'Descripción', 'Cantidad', 'Fecha Ingreso', 'Opciones'],
  },
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verINV',
      name: 'ver',
      value: 'registrarInventarioExterno',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idINV',
      name: 'id',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idusuarioINV',
      name: 'idusuario',
      value: idusuario,
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idclienteINV',
      name: 'idcliente',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idsucursalINV',
      name: 'sucursal',
      value: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select',
      label: 'AlmacenINV',
      titulo: 'Almacén*',
      type: 'select',
      id: 'almacenINV',
      name: 'almacen',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select2',
      label: 'clientesINV',
      titulo: 'Cliente*',
      type: 'text',
      id: 'clientesINV',
      name: 'clientes',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'select2',
      label: 'sucursalINV',
      titulo: 'Sucursal del cliente*',
      type: 'text',
      id: 'sucursalINV',
      name: 'sucursali',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'fechaINV',
      titulo: 'Fecha*',
      type: 'date',
      id: 'fechaINV',
      name: 'fecha',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 4,
      modelo: 'text',
      label: 'imagenINV',
      titulo: 'Imagen*',
      type: 'file',
      id: 'imagenINV',
      name: 'imagen',
      placeholder: '',
      required: false,
      disabled: false,
    },
    {
      tamaño: 12,
      modelo: 'text',
      label: 'observacionINV',
      titulo: 'Observación*',
      type: 'text',
      id: 'observacionINV',
      name: 'observacion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
  fields2: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verDINV',
      name: 'ver',
      value: 'registrarDetalleInvexterno',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idinvexternoDINV',
      name: 'idinventarioexterno',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idproductoalmacenDINV',
      name: 'idproductoalmacen',
      value: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'select2',
      label: 'productosDINV',
      titulo: 'Producto*',
      type: 'text',
      id: 'productosDINV',
      name: 'productos',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'cantidaDINV',
      titulo: 'Cantidad*',
      type: 'text',
      id: 'cantidadDINV',
      name: 'cantidad',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'fechaDINV',
      titulo: 'Fecha*',
      type: 'date',
      id: 'fechaDINV',
      name: 'fecha',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const mermasF = {
  tableHeader: {
    columns: ['N°', 'Fecha', 'Almacén', 'Descripción', 'Autorización', 'Detalle', 'Opciones'],
  },
  nroColumns: 2,
  tableHeaderForm: {
    columns: ['N°', 'Código', 'Descripción', 'Cantidad', 'Opciones'],
  },
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verMER',
      name: 'ver',
      value: 'registrarmerma',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idMER',
      name: 'id',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idusuarioMER',
      name: 'idusuario',
      value: idusuario,
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'fechaMER',
      titulo: 'Fecha*',
      type: 'date',
      id: 'fechaMER',
      name: 'fecha',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'select',
      label: 'almacenMER',
      titulo: 'Almacén*',
      type: 'select',
      id: 'almacenMER',
      name: 'almacen',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'text',
      label: 'descripcionMER',
      titulo: 'Descripcion*',
      type: 'text',
      id: 'descripcionMER',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
  fields2: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verMERD',
      name: 'ver',
      value: 'registrarDetallemerma',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idmermaMERD',
      name: 'idmerma',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idproductoalmacenMERD',
      name: 'idproductoalmacen',
      value: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'select2',
      label: 'productosMERD',
      titulo: 'Producto*',
      type: 'text',
      id: 'productosMERD',
      name: 'productos',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'stockMERD',
      titulo: 'Stock Actual*',
      type: 'text',
      id: 'stockMERD',
      name: '',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'cantidaMERD',
      titulo: 'Cantidad*',
      type: 'text',
      id: 'cantidadMERD',
      name: 'cantidad',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}

export const robosF = {
  tableHeader: {
    columns: ['N°', 'Fecha', 'Almacén', 'Descripción', 'Autorización', 'Detalle', 'Opciones'],
  },
  nroColumns: 2,
  tableHeaderForm: {
    columns: ['N°', 'Código', 'Descripción', 'Cantidad', 'Opciones'],
  },
  fields: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verROB',
      name: 'ver',
      value: 'registrarrobos',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idROB',
      name: 'id',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idusuarioROB',
      name: 'idusuario',
      value: idusuario,
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'text',
      label: 'fechaROB',
      titulo: 'Fecha*',
      type: 'date',
      id: 'fechaROB',
      name: 'fecha',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 3,
      modelo: 'select',
      label: 'almacenROB',
      titulo: 'Almacén*',
      type: 'select',
      id: 'almacenROB',
      name: 'almacen',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'text',
      label: 'descripcionROB',
      titulo: 'Descripción*',
      type: 'text',
      id: 'descripcionROB',
      name: 'descripcion',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
  fields2: [
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'verROBD',
      name: 'ver',
      value: 'registrarDetallerobos',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idmermaROBD',
      name: 'idrobo',
      value: '',
      required: true,
      disabled: false,
    },
    {
      modelo: 'hidden',
      label: '',
      titulo: '',
      type: 'hidden',
      id: 'idproductoalmacenROBD',
      name: 'idproductoalmacen',
      value: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 6,
      modelo: 'select2',
      label: 'productosROBD',
      titulo: 'Producto*',
      type: 'text',
      id: 'productosROBD',
      name: 'productos',
      placeholder: '',
      required: true,
      disabled: false,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'stockROBD',
      titulo: 'Stock Actual*',
      type: 'text',
      id: 'stockROBD',
      name: '',
      placeholder: '',
      required: true,
      disabled: true,
    },
    {
      tamaño: 2,
      modelo: 'text',
      label: 'cantidaROBD',
      titulo: 'Cantidad*',
      type: 'text',
      id: 'cantidadROBD',
      name: 'cantidad',
      placeholder: '',
      required: true,
      disabled: false,
    },
  ],
}
