let venta = {
  //ver: 'registroVenta', //
  //tipoventa: '1',
  //idusuario: 'a8f15eda80c50adb0e71943adc8015cf',
  //idempresa: 'ad61ab143223efbc24c7d2583be69251',
  //idcliente: '413',
  //sucursal: '150',
  //tipodoc: '1',
  //nrodoc: '4473574',
  //fecha: '2025-09-05',
  //puntoventa: '8',
  //metodoPago: '34',
  //canal: '4',
  ///***tipopago: 'contado',
  //***periodopersonalizado: '0',
  jsonDetalles: {
    listaProductos: [
      {
        idproductoalmacen: '4303',
        cantidad: 1,
        precio: '50',
        idstock: '49517',
        idporcentaje: '193',
        candiponible: '0',
        descripcion: 'Café Alto Madidi, Molido, 340gr',
        codigo: 'CAM-03',
        subtotal: 50,
        datosAdicionales: '23911-107900-4-',
        despachado: 1,
      },
    ],
    listaProductosFactura: [
      {
        //                                                                        codigoProducto: 'CAM03-',
        //                                                                        codigoActividadSin: '107900',
        //                                                                        codigoProductoSin: '23911',
        //                                                                        descripcion: 'Café Alto Madidi, Molido, 340gr',
        //                                                                        unidadMedida: '4',
        //                                                                        precioUnitario: '50',
        //                                                                        subTotal: '50.00',
        //                                                                        cantidad: 1,
        //                                                                        numeroSerie: '',
        //                                                                        montoDescuento: 0,
        //                                                                        numeroImei: '',
        //                                                                        codigoNandina: '',
      },
    ],
    listaFactura: {
      // numeroFactura: '',
      //nombreRazonSocial: 'Juan José Nuñez Campero',
      //codigoPuntoVenta: '8',
      //fechaEmision: '2025-09-05T17:35:30.078Z',
      //cafc: '',
      codigoExcepcion: '',
      descuentoAdicional: 0,
      montoGiftCard: 0,
      // codigoTipoDocumentoIdentidad: '1',
      // numeroDocumento: '4473574',
      complemento: '',
      //codigoCliente: 'JO-550120',
      periodoFacturado: '',
      //codigoMetodoPago: '6',
      numeroTarjeta: '',
      //montoTotal: '115.00',
      //codigoMoneda: 1,
      // montoTotalMoneda: '115.00',
      //usuario: 'soporte74',
      //emailCliente: 'factura@yofinanciero.com',
      //telefonoCliente: '',
      // extras: {
      //   facturaTicket: '',
      // },
      //montoTotalSujetoIva: '115.00',
      tipoCambio: 1,
      detalles: [
        /*{
                                                                              codigoProducto: 'CAM-03',
                                                                              codigoActividadSin: '107900',
                                                                              codigoProductoSin: '23911',
                                                                              descripcion: 'Café Alto Madidi, Molido, 340gr',
                                                                              unidadMedida: '4',
                                                                              precioUnitario: '50',
                                                                              subTotal: '50.00',
                                                                              cantidad: 1,
                                                                              numeroSerie: '',
                                                                              montoDescuento: 0,
                                                                              numeroImei: '',
                                                                              codigoNandina: '',
        },
        {
          codigoProducto: 'TEL-01',
          codigoActividadSin: '107900',
          codigoProductoSin: '99100',
          descripcion: 'Tazas eléctricas',
          unidadMedida: '47',
          precioUnitario: '65',
          subTotal: '65.00',
          cantidad: 1,
          numeroSerie: '',
          montoDescuento: 0,
          numeroImei: '',
          codigoNandina: '',
        },*/
      ],
    },
    //idalmacen: '84',
    //codigosinsucursal: '0',
    //token:'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzMDAyMzIiLCJqdGkiOiJiMGM2MzI0Zjc2YTdiZmIwNzliYWRiMjIxM2E3MTQzMmFjYjg2MjlhMzA2YzZmZTY0ODAxNzBlNTFmMTRlYWU4ZTkwZDk3N2NjMDM2MTdmNCIsImlhdCI6MTcyNzQ3NTUyMywibmJmIjoxNzI3NDc1NTIzLCJleHAiOjE3NTkwMTE1MjMsInN1YiI6IiIsInNjb3BlcyI6W119.llLu_9D8mxSjwd3YsvNaFf5-OJWq3IUi5OnrYpwxLd8z-TNh4KlRpAS1RSmphcnc-wtaPoUsv5IisoXCrIvlC6vgLeCFgu92p3pijETH7usOALsFIPDxAgsAvVAxRvuDWP_CdpxH_2VbpmaLLYVtWGAu3nCvCGIC5JczO0ykxli_ruEN_WtcRVDWBig6n40MgQUks__1xRXw-ZG8Y1C6_Y2xJ87xP-5nJXalFbyj6PVK_GBx1Gw6e_So5X5Fl_RLrIqJ4eCkcalkezc3GRnEswusRx6H__93u2vWD1v7Wp5EkVGrGhU0cmSt_FTL753WfuKXfBW-gAFbAj3OMDG5yagd8MU3TvO2fkOdEw0CGhs4bTN9b6QVBygFXA1-k68wTBNyu7xkfN5-4u0YsglUm6uJd9p6gnfAg6mqpg6F7BDM3kNX_0JEaNlCauUhc-30fx83mVeS3d4r8jtEFjKGd2c4QSWn-_H-fR742J7rPOC_8BA8SmO10zUVWBiNkCZ1tsdDsmPyqIVFvXFBfw6VZHtHlFCKxOSiaoJRF--bO04XzLBQRm2jXsKMLgSg6Jd1lZQ-8Y8_OguMqMZd2GVnHezk5OSKDOafUQjiGlGNDGqQPJfw8I7t3b3_Jzgd0ZmsNVUdRd7uS1xrS_NOzff1uLfCPUxJObK6HPfqudZFoSQ',
    //tipoFactura: '2',
    iddivisa: 31,
    //idcampana: 0,
    //ventatotal: '115.00',
    //subtotal: '115.00',
    //descuento: 0,

    //nropagos: 0,
    //valorpagos: 0,
    //dias: null,
    //fechalimite: '',
    // pagosDivididos: [
    //   {
    //     metodoPago: {
    //       label: 'Venta a crédito',
    //       id: 34,
    //       value: '6',
    //     },
    //     monto: '115.00',
    //     porcentaje: 100,
    //   },
    // ],
    // variablePago: 'dividido',
  },
}
console.log(venta)
